export const smilesTags = new Map([
    [
        "пека",
        [
            ":peka:",
            ":ohmypeka:",
            ":scarypeka:",
            ":pekaclap:",
            ":comf:",
            ":pled:",
            ":gravitypeka:",
            ":insanepeka:",
        ],
    ],
    [
        "йоба",
        [
            ":peka:",
            ":ohmypeka:",
            ":scarypeka:",
            ":pekaclap:",
            ":comf:",
            ":pled:",
            ":gravitypeka:",
            ":insanepeka:",
        ],
    ],
    [
        "колобок",
        [
            ":peka:",
            ":ohmypeka:",
            ":scarypeka:",
            ":pekaclap:",
            ":comf:",
            ":pled:",
            ":gravitypeka:",
            ":insanepeka:",
            ":rofl:",
            ":omg:",
            ":shocked:",
            ":wonder:",
            ":daun:",
            ":panic:",
            ":huh:",
            ":sosp:",
            ":notfunny:",
            ":cry:",
            ":cryalot:",
            ":cool:",
            ":sad:",
            ":smilegasm:",
            ":marvelous:",
            ":happyface:",
            ":geek:",
            ":sic:",
            ":kiss:",
            ":yazik:",
            ":zzz:",
            ":angry:",
            ":rage:",
            ":skull:",
        ],
    ],
    [
        "peka",
        [
            ":peka:",
            ":ohmypeka:",
            ":scarypeka:",
            ":pekaclap:",
            ":comf:",
            ":pled:",
            ":gravitypeka:",
            ":insanepeka:",
        ],
    ],
    ["браво", [":pekaclap:", ":bravo:"]],
    ["хлоп", [":pekaclap:", ":bravo:"]],
    ["комфор", [":comf:", ":pled:"]],
    ["плед", [":comf:", ":pled:", ":comfort:"]],
    ["погод", [":comf:", ":pled:", ":gosling:", ":comfort:"]],
    ["яблоко", [":gravitypeka:"]],
    ["гравитация", [":gravitypeka:"]],
    ["падение", [":gravitypeka:"]],
    ["упал", [":gravitypeka:"]],
    ["рофл", [":rofl:"]],
    ["rofl", [":rofl:"]],
    ["omg", [":omg:"]],
    ["омг", [":omg:"]],
    ["шок", [":shocked:"]],
    ["шокирован", [":shocked:"]],
    ["шокед", [":shocked:"]],
    ["shocked", [":shocked:"]],
    ["интересно", [":wonder:", ":cboring:"]],
    ["хмм", [":wonder:", ":huh:", ":hmmm:"]],
    ["wonder", [":wonder:"]],
    ["глупость", [":daun:"]],
    ["глуп", [":daun:"]],
    ["улыбка", [":daun:"]],
    ["паника", [":panic:"]],
    ["panic", [":panic:"]],
    ["huh", [":huh:"]],
    ["подозр", [":sosp:", ":search:", ":hmmm:"]],
    ["подозрительный", [":sosp:"]],
    ["susp", [":sosp:"]],
    ["notfunny", [":notfunny:"]],
    ["несмешн", [":notfunny:"]],
    ["не", [":notfunny:"]],
    ["cry", [":cry:", ":cryalot:"]],
    ["слез", [":cry:", ":cryalot:"]],
    ["плак", [":cry:", ":cryalot:", ":sad:", ":chmis:", ":pepehands:"]],
    ["плач", [":cry:", ":cryalot:", ":sad:", ":chmis:", ":pepehands:"]],
    ["грус", [":cry:", ":cryalot:", ":sad:", ":chmis:", ":kerrisad:"]],
    ["cool", [":cool:"]],
    ["крут", [":cool:", ":gosling:", ":myway:", ":clear:"]],
    ["sad", [":sad:"]],
    ["smilegasm", [":smilegasm:"]],
    ["клас", [":smilegasm:", ":marvelous:"]],
    ["нрав", [":smilegasm:", ":marvelous:", ":happyface:"]],
    ["оргазм", [":smilegasm:", ":marvelous:"]],
    ["довол", [":smilegasm:", ":marvelous:", ":happyface:", ":goodboy:"]],
    ["счас", [":smilegasm:", ":marvelous:", ":happyface:"]],
    ["marvelous", [":marvelous:"]],
    ["happyface", [":happyface:"]],
    ["счаст", [":happyface:"]],
    ["улыб", [":happyface:"]],
    ["geek", [":geek:"]],
    ["очки", [":geek:"]],
    ["ум", [":geek:"]],
    ["эксперт", [":geek:", ":master:", ":tactics:"]],
    ["учен", [":geek:"]],
    ["наука", [":geek:", ":pigeon:"]],
    ["ботан", [":geek:", ":hacking:"]],
    ["гик", [":geek:", ":hacking:"]],
    ["sic", [":sic:"]],
    ["боль", [":sic:"]],
    ["здоров", [":sic:", ":bandages:", ":heal:", ":bodyb:", ":runway:"]],
    ["блев", [":sic:"]],
    ["фу", [":sic:", ":catyuck:"]],
    ["тошн", [":sic:"]],
    ["kiss", [":kiss:"]],
    ["поцел", [":kiss:"]],
    ["цел", [":kiss:"]],
    ["люб", [":kiss:"]],
    ["чмок", [":kiss:"]],
    ["yazik", [":yazik:"]],
    ["дразн", [":yazik:"]],
    ["язык", [":yazik:"]],
    ["бе", [":yazik:"]],
    ["zzz", [":zzz:"]],
    ["устал", [":zzz:"]],
    ["спать", [":zzz:"]],
    ["уснул", [":zzz:"]],
    ["сон", [":zzz:"]],
    ["спит", [":zzz:"]],
    ["скучно", [":zzz:", ":cboring:"]],
    ["интерес", [":zzz:"]],
    ["angry", [":angry:"]],
    [
        "злой",
        [":angry:", ":rage:", ":damn:", ":nope:", ":fuckoff:", ":nofeels:"],
    ],
    ["злость", [":angry:", ":rage:"]],
    ["бомб", [":angry:", ":rage:"]],
    ["ярость", [":angry:", ":rage:"]],
    ["гор", [":angry:", ":rage:", ":thisisfine:"]],
    ["rage", [":rage:"]],
    ["пригор", [":rage:"]],
    ["подгор", [":rage:"]],
    ["skull", [":skull:"]],
    ["умер", [":skull:"]],
    ["смер", [":skull:"]],
    ["помер", [":skull:"]],
    ["гуф", [":skull:"]],
    ["гг", [":skull:"]],
    [
        "бобр",
        [
            ":damn:",
            ":hug:",
            ":merchant:",
            ":chomander:",
            ":boy:",
            ":flamer:",
            ":bvecher:",
            ":sir:",
            ":busted:",
            ":bobrpirat:",
            ":oneone:",
            ":fsb:",
            ":pun:",
            ":bandages:",
            ":winner:",
            ":waiting:",
            ":buggy:",
            ":loot:",
            ":megafon:",
            ":toohot:",
            ":snow:",
            ":heal:",
            ":pigeon:",
            ":www:",
            ":flowers:",
            ":fight:",
            ":darthbobr:",
            ":nosound:",
            ":nichobobr:",
            ":jasonbobr:",
            ":beverly:",
            ":alwayshb:",
        ],
    ],
    [
        "бобер",
        [
            ":damn:",
            ":hug:",
            ":merchant:",
            ":chomander:",
            ":boy:",
            ":flamer:",
            ":bvecher:",
            ":sir:",
            ":busted:",
            ":bobrpirat:",
            ":oneone:",
            ":fsb:",
            ":pun:",
            ":bandages:",
            ":winner:",
            ":waiting:",
            ":buggy:",
            ":loot:",
            ":megafon:",
            ":toohot:",
            ":snow:",
            ":heal:",
            ":pigeon:",
            ":www:",
            ":flowers:",
            ":fight:",
            ":darthbobr:",
            ":nosound:",
            ":nichobobr:",
            ":jasonbobr:",
            ":beverly:",
            ":alwayshb:",
        ],
    ],
    [
        "bobr",
        [
            ":damn:",
            ":hug:",
            ":merchant:",
            ":chomander:",
            ":boy:",
            ":flamer:",
            ":bvecher:",
            ":sir:",
            ":busted:",
            ":bobrpirat:",
            ":oneone:",
            ":fsb:",
            ":pun:",
            ":bandages:",
            ":winner:",
            ":waiting:",
            ":buggy:",
            ":loot:",
            ":megafon:",
            ":toohot:",
            ":snow:",
            ":heal:",
            ":pigeon:",
            ":www:",
            ":flowers:",
            ":fight:",
            ":darthbobr:",
            ":nosound:",
            ":nichobobr:",
            ":jasonbobr:",
            ":beverly:",
            ":alwayshb:",
        ],
    ],
    ["черт", [":damn:"]],
    ["damn", [":damn:"]],
    [
        "кот",
        [
            ":hug:",
            ":cboring:",
            ":buffering:",
            ":cscare:",
            ":cooper:",
            ":mae:",
            ":smudge:",
            ":turbo:",
            ":bravo:",
            ":hey:",
            ":sushicat:",
            ":flashl:",
            ":noted:",
            ":catrain:",
            ":giftcat:",
            ":gta:",
            ":nope:",
            ":snow2:",
            ":bodyb:",
            ":runway:",
            ":aweasome:",
            ":whyyy:",
            ":yoyo:",
            ":selfie:",
            ":search:",
            ":plasma:",
            ":cat:",
            ":catyes:",
            ":catno:",
            ":catyuck:",
            ":badumtss:",
            ":bdbessa:",
            ":bessa:",
            ":catouh:",
            ":grumpy:",
            ":fuckoff:",
            ":nofeels:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
        ],
    ],
    [
        "cat",
        [
            ":hug:",
            ":cboring:",
            ":buffering:",
            ":cscare:",
            ":cooper:",
            ":mae:",
            ":smudge:",
            ":turbo:",
            ":bravo:",
            ":hey:",
            ":sushicat:",
            ":flashl:",
            ":noted:",
            ":catrain:",
            ":giftcat:",
            ":gta:",
            ":nope:",
            ":snow2:",
            ":bodyb:",
            ":runway:",
            ":aweasome:",
            ":whyyy:",
            ":yoyo:",
            ":selfie:",
            ":search:",
            ":plasma:",
            ":cat:",
            ":catyes:",
            ":catno:",
            ":catyuck:",
            ":badumtss:",
            ":bdbessa:",
            ":bessa:",
            ":catouh:",
            ":grumpy:",
            ":fuckoff:",
            ":nofeels:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
        ],
    ],
    ["hug", [":hug:"]],
    ["обни", [":hug:"]],
    ["обня", [":hug:"]],
    ["объят", [":hug:"]],
    ["торг", [":merchant:"]],
    ["мерч", [":merchant:"]],
    ["resident", [":merchant:"]],
    ["buy", [":merchant:"]],
    ["купить", [":merchant:"]],
    ["commander", [":chomander:"]],
    ["чомандер", [":chomander:", ":gta:"]],
    ["команд", [":chomander:", ":gta:"]],
    ["xcom", [":chomander:"]],
    ["boy", [":boy:"]],
    ["gow", [":boy:"]],
    ["god", [":boy:"]],
    ["sony", [":boy:"]],
    ["playstation", [":boy:"]],
    ["щегол", [":boy:"]],
    ["пацан", [":boy:"]],
    ["flamer", [":flamer:"]],
    ["огнемет", [":flamer:"]],
    ["мерз", [":flamer:"]],
    ["ужас", [":flamer:", ":monkas:"]],
    ["сжечь", [":flamer:"]],
    ["ересь", [":flamer:"]],
    ["бобрый", [":bvecher:", ":hey:"]],
    ["добрый", [":bvecher:", ":hey:"]],
    ["привет", [":bvecher:", ":hey:"]],
    ["здаров", [":bvecher:", ":hey:"]],
    ["здравствуй", [":bvecher:", ":hey:"]],
    ["вечер", [":bvecher:", ":hey:"]],
    ["сэр", [":sir:"]],
    ["sir", [":sir:"]],
    ["сноб", [":sir:"]],
    ["моноколь", [":sir:"]],
    ["господ", [":sir:"]],
    ["сарказм", [":sir:", ":badumtss:"]],
    ["busted", [":busted:"]],
    ["полиция", [":busted:"]],
    ["караул", [":busted:"]],
    ["наруш", [":busted:"]],
    ["внимание", [":busted:", ":megafon:"]],
    ["милиц", [":busted:"]],
    ["свист", [":busted:"]],
    ["pirat", [":bobrpirat:"]],
    ["пират", [":bobrpirat:"]],
    ["торрент", [":bobrpirat:"]],
    ["аббордаж", [":bobrpirat:"]],
    ["хохо", [":bobrpirat:"]],
    ["первый", [":oneone:", ":winner:"]],
    [
        "победа",
        [
            ":oneone:",
            ":winner:",
            ":www:",
            ":fight:",
            ":darthbobr:",
            ":bravo:",
        ],
    ],
    [
        "топ",
        [
            ":oneone:",
            ":winner:",
            ":www:",
            ":fight:",
            ":darthbobr:",
            ":bravo:",
            ":clear:",
            ":mcomplete:",
            ":overfan:",
        ],
    ],
    ["выигр", [":oneone:", ":winner:", ":fight:", ":darthbobr:"]],
    ["лучший", [":oneone:", ":winner:", ":fight:", ":darthbobr:", ":bravo:"]],
    ["фсб", [":fsb:"]],
    ["служб", [":fsb:"]],
    ["слеж", [":fsb:"]],
    ["следим", [":fsb:"]],
    ["слушаем", [":fsb:"]],
    [
        "мем",
        [
            ":fsb:",
            ":nichobobr:",
            ":jasonbobr:",
            ":beverly:",
            ":alwayshb:",
            ":smudge:",
            ":gta:",
            ":whyyy:",
            ":plasma:",
            ":badumtss:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
            ":doggie:",
            ":chmis:",
            ":forespect:",
            ":thisisfine:",
            ":pepelaugh:",
            ":pepehands:",
            ":poggers:",
            ":monkas:",
            ":pepoclown:",
            ":fibo:",
            ":fibod:",
            ":fffibo:",
            ":ledokol:",
            ":lk:",
        ],
    ],
    ["сковорода", [":pun:"]],
    ["любл", [":pun:", ":flowers:", ":nofeels:"]],
    [
        "пубг",
        [":pun:", ":bandages:", ":winner:", ":waiting:", ":buggy:", ":loot:"],
    ],
    [
        "pubg",
        [":pun:", ":bandages:", ":winner:", ":waiting:", ":buggy:", ":loot:"],
    ],
    ["бинт", [":bandages:"]],
    ["хил", [":bandages:", ":heal:"]],
    ["лечение", [":bandages:", ":heal:"]],
    ["апте", [":bandages:", ":heal:"]],
    ["снайпер", [":waiting:"]],
    ["засада", [":waiting:"]],
    ["жду", [":waiting:"]],
    ["крыс", [":waiting:"]],
    ["рыбалка", [":waiting:"]],
    ["ехать", [":buggy:"]],
    ["поехали", [":buggy:", ":turbo:"]],
    ["маши", [":buggy:", ":turbo:", ":myway:"]],
    ["выезж", [":buggy:", ":turbo:"]],
    ["еду", [":buggy:", ":turbo:"]],
    ["buggy", [":buggy:"]],
    ["багги", [":buggy:"]],
    ["loot", [":loot:"]],
    ["лут", [":loot:", ":doornoloot:"]],
    ["готов", [":loot:"]],
    ["хэд", [":loot:"]],
    ["объяв", [":megafon:"]],
    ["мегафон", [":megafon:"]],
    ["кри", [":megafon:"]],
    ["громко", [":megafon:"]],
    ["душ", [":toohot:"]],
    ["дух", [":toohot:"]],
    ["жарко", [":toohot:"]],
    ["зануда", [":toohot:"]],
    ["снег", [":snow:", ":snow2:"]],
    ["зима", [":snow:"]],
    ["новый", [":snow:", ":snow2:"]],
    ["нг", [":snow:", ":snow2:"]],
    ["погода", [":snow:", ":catrain:", ":snow2:"]],
    ["лечи", [":heal:"]],
    ["бабочка", [":pigeon:"]],
    ["радость", [":www:", ":cooper:", ":bravo:", ":giftcat:", ":badumtss:"]],
    ["цветы", [":flowers:"]],
    ["любо", [":flowers:", ":nofeels:"]],
    ["смешно", [":fight:", ":nichobobr:", ":badumtss:"]],
    ["сраже", [":fight:"]],
    ["звездн", [":darthbobr:"]],
    ["тихо", [":nosound:"]],
    ["микр", [":nosound:"]],
    ["слышно", [":nosound:"]],
    ["выкл", [":nosound:"]],
    ["ничоси", [":nichobobr:"]],
    ["wow", [":nichobobr:", ":aweasome:", ":yoyo:", ":doggie:", ":poggers:"]],
    ["джейсон", [":jasonbobr:"]],
    ["jason", [":jasonbobr:"]],
    ["мясо", [":jasonbobr:"]],
    ["ныть", [":beverly:", ":catyuck:"]],
    ["вайн", [":beverly:"]],
    ["всегда", [":alwayshb:"]],
    ["поворот", [":alwayshb:"]],
    [
        "кош",
        [
            ":cboring:",
            ":buffering:",
            ":cscare:",
            ":cooper:",
            ":mae:",
            ":smudge:",
            ":turbo:",
            ":bravo:",
            ":hey:",
            ":sushicat:",
            ":flashl:",
            ":noted:",
            ":catrain:",
            ":giftcat:",
            ":gta:",
            ":nope:",
            ":snow2:",
            ":bodyb:",
            ":runway:",
            ":aweasome:",
            ":whyyy:",
            ":yoyo:",
            ":selfie:",
            ":search:",
            ":plasma:",
            ":cat:",
            ":catyes:",
            ":catno:",
            ":catyuck:",
            ":badumtss:",
            ":bdbessa:",
            ":bessa:",
            ":catouh:",
            ":grumpy:",
            ":fuckoff:",
            ":nofeels:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
        ],
    ],
    [
        "современии",
        [
            ":cboring:",
            ":buffering:",
            ":cscare:",
            ":cooper:",
            ":mae:",
            ":smudge:",
            ":turbo:",
            ":bravo:",
            ":hey:",
            ":sushicat:",
            ":flashl:",
            ":noted:",
            ":catrain:",
            ":giftcat:",
            ":gta:",
            ":nope:",
            ":snow2:",
            ":bodyb:",
            ":runway:",
            ":aweasome:",
            ":whyyy:",
            ":yoyo:",
            ":selfie:",
            ":search:",
            ":plasma:",
            ":cat:",
            ":catyes:",
            ":catno:",
            ":catyuck:",
            ":badumtss:",
            ":bdbessa:",
            ":bessa:",
            ":catouh:",
            ":grumpy:",
            ":fuckoff:",
            ":nofeels:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
        ],
    ],
    [
        "мяу",
        [
            ":cboring:",
            ":buffering:",
            ":cscare:",
            ":cooper:",
            ":mae:",
            ":smudge:",
            ":turbo:",
            ":bravo:",
            ":hey:",
            ":sushicat:",
            ":flashl:",
            ":noted:",
            ":catrain:",
            ":giftcat:",
            ":gta:",
            ":nope:",
            ":snow2:",
            ":bodyb:",
            ":runway:",
            ":aweasome:",
            ":whyyy:",
            ":yoyo:",
            ":selfie:",
            ":search:",
            ":plasma:",
            ":cat:",
            ":catyes:",
            ":catno:",
            ":catyuck:",
            ":badumtss:",
            ":bdbessa:",
            ":bessa:",
            ":catouh:",
            ":grumpy:",
            ":fuckoff:",
            ":nofeels:",
            ":whaat:",
            ":vjuh:",
            ":vjoh:",
            ":getout:",
            ":ufreddie:",
        ],
    ],
    ["буф", [":buffering:"]],
    ["загруз", [":buffering:"]],
    ["понял", [":buffering:", ":noted:", ":whaat:"]],
    ["непонял", [":buffering:", ":smudge:", ":whaat:"]],
    ["не понял", [":buffering:"]],
    ["страх", [":cscare:", ":runway:", ":sif:", ":monkas:"]],
    ["страш", [":cscare:", ":runway:", ":monkas:"]],
    ["пистолет", [":cscare:"]],
    ["огонь", [":cscare:", ":bessa:", ":thisisfine:"]],
    ["доволь", [":cooper:", ":grumpy:"]],
    ["чай", [":cooper:", ":mae:"]],
    ["кофе", [":cooper:"]],
    ["пить", [":cooper:"]],
    ["пье", [":cooper:"]],
    ["мое", [":mae:"]],
    ["жадн", [":mae:"]],
    ["еда", [":mae:", ":sushicat:"]],
    ["nfs", [":turbo:"]],
    ["turbo", [":turbo:"]],
    ["апплодисменты", [":bravo:"]],
    ["bravo", [":bravo:"]],
    ["hey", [":hey:"]],
    ["хэй", [":hey:"]],
    ["хей", [":hey:"]],
    ["суши", [":sushicat:"]],
    ["рыб", [":sushicat:"]],
    ["sushi", [":sushicat:"]],
    ["фото", [":flashl:", ":selfie:"]],
    ["вспышка", [":flashl:", ":selfie:"]],
    ["ярко", [":flashl:"]],
    ["флеш", [":flashl:"]],
    ["flash", [":flashl:"]],
    ["noted", [":noted:"]],
    ["запис", [":noted:"]],
    ["пишу", [":noted:"]],
    ["блокнот", [":noted:"]],
    ["понят", [":noted:"]],
    ["помет", [":noted:"]],
    ["грусть", [":catrain:", ":grumpy:", ":pepehands:"]],
    ["дождь", [":catrain:", ":gosling:"]],
    ["подарок", [":giftcat:"]],
    ["гифт", [":giftcat:"]],
    ["gift", [":giftcat:"]],
    ["коробка", [":giftcat:"]],
    ["праздник", [":giftcat:"]],
    ["арстоцка", [":gta:"]],
    ["нет", [":nope:", ":catno:", ":catyuck:"]],
    ["nope", [":nope:"]],
    ["кач", [":bodyb:", ":runway:"]],
    ["зал", [":bodyb:"]],
    ["тренаж", [":bodyb:", ":runway:"]],
    ["тяж", [":bodyb:"]],
    ["бег", [":runway:"]],
    ["беж", [":runway:"]],
    ["круто", [":aweasome:", ":yoyo:"]],
    ["глаза", [":aweasome:"]],
    ["whyy", [":whyyy:"]],
    ["как", [":whyyy:", ":pepehands:"]],
    ["почему", [":whyyy:", ":pepehands:"]],
    ["реп", [":yoyo:"]],
    ["рэп", [":yoyo:"]],
    ["музыка", [":yoyo:", ":catyes:", ":badumtss:", ":ufreddie:"]],
    ["фотк", [":selfie:"]],
    ["ищу", [":search:"]],
    ["поиск", [":search:"]],
    ["лупа", [":search:"]],
    ["найт", [":search:"]],
    ["сыщик", [":search:"]],
    ["plasma", [":plasma:"]],
    ["анклав", [":plasma:"]],
    ["anclav", [":plasma:"]],
    ["да", [":catyes:"]],
    ["yes", [":catyes:"]],
    ["соглас", [":catyes:", ":catno:"]],
    ["точн", [":catyes:", ":calc:"]],
    ["no", [":catno:"]],
    ["бэс", [":bdbessa:", ":bessa:", ":vjoh:"]],
    ["бес", [":bdbessa:", ":bessa:", ":vjoh:"]],
    ["черн", [":bdbessa:", ":bessa:"]],
    ["ухх", [":catouh:"]],
    ["уф", [":catouh:"]],
    ["хочу", [":catouh:"]],
    ["грумп", [":grumpy:"]],
    ["grumpy", [":grumpy:"]],
    ["отстань", [":fuckoff:", ":nofeels:"]],
    ["фак", [":fuckoff:"]],
    ["fuck", [":fuckoff:"]],
    ["че", [":whaat:"]],
    ["что", [":whaat:"]],
    ["чаво", [":whaat:"]],
    ["магия", [":vjuh:", ":vjoh:"]],
    ["колд", [":vjuh:", ":vjoh:", ":archmage:"]],
    ["вжух", [":vjuh:", ":vjoh:"]],
    ["уходи", [":getout:"]],
    ["вали", [":getout:"]],
    ["у-", [":getout:"]],
    ["фред", [":ufreddie:"]],
    [
        "соб",
        [
            ":shenok:",
            ":sif:",
            ":goodboy:",
            ":hacking:",
            ":gosling:",
            ":strelka:",
            ":belka:",
            ":doggie:",
            ":master:",
            ":chmis:",
            ":detective:",
            ":forespect:",
            ":lagdog:",
            ":myway:",
            ":clear:",
            ":mcomplete:",
            ":sigh:",
            ":thisisfine:",
            ":sing:",
            ":tactics:",
            ":support:",
            ":comfort:",
            ":dog2:",
            ":calc:",
            ":zerg:",
        ],
    ],
    [
        "пес",
        [
            ":shenok:",
            ":sif:",
            ":goodboy:",
            ":hacking:",
            ":gosling:",
            ":strelka:",
            ":belka:",
            ":doggie:",
            ":master:",
            ":chmis:",
            ":detective:",
            ":forespect:",
            ":lagdog:",
            ":myway:",
            ":clear:",
            ":mcomplete:",
            ":sigh:",
            ":thisisfine:",
            ":sing:",
            ":tactics:",
            ":support:",
            ":comfort:",
            ":dog2:",
            ":calc:",
        ],
    ],
    [
        "щенок",
        [
            ":shenok:",
            ":sif:",
            ":goodboy:",
            ":hacking:",
            ":gosling:",
            ":strelka:",
            ":belka:",
            ":doggie:",
            ":master:",
            ":chmis:",
            ":detective:",
            ":forespect:",
            ":lagdog:",
            ":myway:",
            ":clear:",
            ":mcomplete:",
            ":sigh:",
            ":thisisfine:",
            ":sing:",
            ":tactics:",
            ":support:",
            ":comfort:",
            ":dog2:",
            ":calc:",
        ],
    ],
    [
        "гаф",
        [
            ":shenok:",
            ":sif:",
            ":hacking:",
            ":gosling:",
            ":strelka:",
            ":belka:",
            ":doggie:",
            ":master:",
            ":chmis:",
            ":detective:",
            ":forespect:",
            ":lagdog:",
            ":myway:",
            ":clear:",
            ":mcomplete:",
            ":sigh:",
            ":thisisfine:",
            ":sing:",
            ":tactics:",
            ":support:",
            ":comfort:",
            ":dog2:",
            ":calc:",
        ],
    ],
    [
        "гав",
        [
            ":shenok:",
            ":sif:",
            ":hacking:",
            ":gosling:",
            ":strelka:",
            ":belka:",
            ":doggie:",
            ":master:",
            ":chmis:",
            ":detective:",
            ":forespect:",
            ":lagdog:",
            ":myway:",
            ":clear:",
            ":mcomplete:",
            ":sigh:",
            ":thisisfine:",
            ":sing:",
            ":tactics:",
            ":support:",
            ":comfort:",
            ":dog2:",
            ":calc:",
        ],
    ],
    ["босс", [":sif:"]],
    ["goodboy", [":goodboy:"]],
    ["хороший", [":goodboy:"]],
    ["мальчик", [":goodboy:"]],
    ["лапки", [":goodboy:"]],
    ["hacking", [":hacking:"]],
    ["взлом", [":hacking:"]],
    ["хак", [":hacking:"]],
    ["чит", [":hacking:"]],
    ["комп", [":hacking:"]],
    ["синт", [":hacking:"]],
    ["gosling", [":gosling:"]],
    ["гослинг", [":gosling:"]],
    ["strelka", [":strelka:"]],
    ["стрелка", [":strelka:"]],
    ["косм", [":strelka:", ":belka:"]],
    ["хорош", [":strelka:", ":belka:", ":thisisfine:"]],
    ["belka", [":belka:"]],
    ["белка", [":belka:"]],
    ["doggie", [":doggie:"]],
    ["дог", [":doggie:", ":chmis:"]],
    ["вау", [":doggie:", ":poggers:"]],
    ["master", [":master:"]],
    ["мастер", [":master:"]],
    ["самурай", [":master:"]],
    ["меч", [":master:"]],
    ["chmis", [":chmis:"]],
    ["чимс", [":chmis:"]],
    ["detective", [":detective:"]],
    ["детектив", [":detective:"]],
    ["шерлок", [":detective:"]],
    ["расслед", [":detective:"]],
    ["трубк", [":detective:"]],
    ["forespect", [":forespect:"]],
    ["уваж", [":forespect:"]],
    ["cod", [":forespect:"]],
    ["пресс", [":forespect:"]],
    ["press", [":forespect:"]],
    ["f", [":forespect:"]],
    ["ф", [":forespect:"]],
    ["lagdog", [":lagdog:"]],
    ["лаг", [":lagdog:", ":ledokol:", ":lk:"]],
    ["фриз", [":lagdog:"]],
    ["пинг", [":lagdog:"]],
    ["myway", [":myway:"]],
    ["поех", [":myway:"]],
    ["еде", [":myway:"]],
    ["clear", [":clear:"]],
    ["чисто", [":clear:"]],
    ["про", [":clear:"]],
    ["экспер", [":clear:"]],
    ["побе", [":clear:", ":mcomplete:"]],
    ["mcomplete", [":mcomplete:"]],
    ["миссия", [":mcomplete:"]],
    ["выполне", [":mcomplete:"]],
    ["sigh", [":sigh:"]],
    ["внима", [":sigh:"]],
    ["слуш", [":sigh:", ":sing:", ":support:"]],
    ["ага", [":sigh:"]],
    ["рассказ", [":sigh:"]],
    ["thisisfine", [":thisisfine:"]],
    ["подга", [":thisisfine:"]],
    ["плох", [":thisisfine:"]],
    ["sing", [":sing:"]],
    ["петь", [":sing:"]],
    ["пой", [":sing:"]],
    ["песнь", [":sing:"]],
    ["муз", [":sing:", ":dance:"]],
    ["tactics", [":tactics:"]],
    ["такти", [":tactics:"]],
    ["страт", [":tactics:"]],
    ["support", [":support:"]],
    ["супорт", [":support:"]],
    ["помо", [":support:"]],
    ["важн", [":support:"]],
    ["comfort", [":comfort:"]],
    ["комфорт", [":comfort:"]],
    ["ден", [":comfort:"]],
    ["dog2", [":dog2:"]],
    ["calc", [":calc:"]],
    ["кальк", [":calc:"]],
    ["просчита", [":calc:"]],
    ["расчита", [":calc:"]],
    [
        "пепе",
        [
            ":hmmm:",
            ":pepcard:",
            ":pepelaugh:",
            ":pepehands:",
            ":poggers:",
            ":monkas:",
            ":pepoclown:",
        ],
    ],
    [
        "жабка",
        [
            ":hmmm:",
            ":pepcard:",
            ":pepelaugh:",
            ":pepehands:",
            ":poggers:",
            ":monkas:",
            ":pepoclown:",
        ],
    ],
    [
        "pepe",
        [
            ":hmmm:",
            ":pepcard:",
            ":pepelaugh:",
            ":pepehands:",
            ":poggers:",
            ":monkas:",
            ":pepoclown:",
        ],
    ],
    ["hmmm", [":hmmm:"]],
    ["pepcard", [":pepcard:"]],
    ["деньг", [":pepcard:"]],
    ["бабк", [":pepcard:"]],
    ["дона", [":pepcard:"]],
    ["бога", [":pepcard:"]],
    ["оплат", [":pepcard:"]],
    ["pepelaugh", [":pepelaugh:"]],
    ["смех", [":pepelaugh:"]],
    ["смешн", [":pepelaugh:", ":pepoclown:"]],
    ["радос", [":pepelaugh:"]],
    ["pepehands", [":pepehands:"]],
    ["poggers", [":poggers:"]],
    ["вов", [":poggers:"]],
    ["ух", [":poggers:"]],
    ["monkas", [":monkas:"]],
    ["pepoclown", [":pepoclown:"]],
    ["клоун", [":pepoclown:"]],
    [
        "wc",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
        ],
    ],
    [
        "вар",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
        ],
    ],
    [
        "крафт",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    [
        "war",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
        ],
    ],
    ["sorka", [":sorka:"]],
    [
        "близ",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
            ":deckard:",
            ":tirael:",
            ":diablo:",
            ":gold:",
            ":moo:",
            ":mana:",
            ":valla:",
        ],
    ],
    [
        "blizz",
        [
            ":sorka:",
            ":doornoloot:",
            ":pitlord:",
            ":jobagain:",
            ":archmage:",
            ":acolyte:",
            ":artas:",
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
            ":deckard:",
            ":tirael:",
            ":diablo:",
            ":gold:",
            ":moo:",
            ":mana:",
            ":valla:",
        ],
    ],
    ["не так", [":sorka:"]],
    ["котик", [":sorka:"]],
    ["сорка", [":sorka:"]],
    ["альян", [":sorka:", ":archmage:", ":artas:"]],
    ["doornoloot", [":doornoloot:"]],
    ["двери", [":doornoloot:"]],
    ["не лут", [":doornoloot:"]],
    ["звери", [":doornoloot:"]],
    ["бист", [":doornoloot:"]],
    ["beast", [":doornoloot:"]],
    ["орк", [":doornoloot:", ":jobagain:"]],
    ["pitlord", [":pitlord:"]],
    ["пит", [":pitlord:"]],
    ["пади", [":pitlord:"]],
    ["ниц", [":pitlord:"]],
    ["jobagain", [":jobagain:"]],
    ["раб", [":jobagain:", ":acolyte:"]],
    ["опять", [":jobagain:"]],
    ["пион", [":jobagain:"]],
    ["peon", [":jobagain:"]],
    ["archmage", [":archmage:"]],
    ["маг", [":archmage:"]],
    ["архи", [":archmage:"]],
    ["арк", [":archmage:"]],
    ["гей", [":archmage:"]],
    ["acolyte", [":acolyte:"]],
    ["аколит", [":acolyte:"]],
    ["happy", [":acolyte:"]],
    ["андед", [":acolyte:"]],
    ["artas", [":artas:"]],
    ["артас", [":artas:"]],
    ["сжеч", [":artas:"]],
    ["пал", [":artas:"]],
    [
        "sc",
        [
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    [
        "стар",
        [
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    [
        "star",
        [
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    [
        "ск",
        [
            ":tire:",
            ":pilon:",
            ":toss:",
            ":archon:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    ["tire", [":tire:"]],
    ["шин", [":tire:"]],
    [
        "зерг",
        [
            ":tire:",
            ":dance:",
            ":zerg:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
        ],
    ],
    ["протос", [":tire:", ":pilon:", ":toss:"]],
    [
        "терран",
        [
            ":tire:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    ["pilon", [":pilon:"]],
    ["пилон", [":pilon:"]],
    ["toss", [":toss:"]],
    ["тосс", [":toss:", ":archon:"]],
    ["зилот", [":toss:"]],
    ["archon", [":archon:"]],
    ["протосс", [":archon:"]],
    ["архон", [":archon:"]],
    ["dance", [":dance:"]],
    ["тане", [":dance:"]],
    ["танц", [":dance:"]],
    ["бруд", [":dance:"]],
    [
        "имба",
        [
            ":dance:",
            ":roach:",
            ":overfan:",
            ":kerrievil:",
            ":muta:",
            ":bane:",
            ":kerrisad:",
            ":kerrisad:",
            ":goliath:",
            ":marikbw:",
            ":reynor:",
            ":marik:",
        ],
    ],
    ["zerg", [":zerg:"]],
    ["линг", [":zerg:", ":bane:"]],
    ["roach", [":roach:"]],
    ["роач", [":roach:"]],
    ["роуч", [":roach:"]],
    ["таракан", [":roach:"]],
    ["overfan", [":overfan:"]],
    ["овер", [":overfan:"]],
    ["побед", [":overfan:"]],
    ["gg", [":overfan:"]],
    ["kerrievil", [":kerrievil:"]],
    ["зло", [":kerrievil:"]],
    ["кери", [":kerrievil:", ":kerrisad:"]],
    ["керри", [":kerrievil:", ":kerrisad:"]],
    ["muta", [":muta:"]],
    ["мута", [":muta:"]],
    ["bane", [":bane:"]],
    ["бейн", [":bane:"]],
    ["kerrisad", [":kerrisad:"]],
    ["goliath", [":goliath:"]],
    ["голиф", [":goliath:"]],
    ["marikbw", [":marikbw:"]],
    ["марик", [":marikbw:", ":reynor:", ":marik:"]],
    ["марин", [":marikbw:", ":reynor:", ":marik:"]],
    ["reynor", [":reynor:"]],
    ["рейнор", [":reynor:"]],
    ["фибо", [":fibo:", ":fibod:", ":fffibo:"]],
    ["и так", [":fibo:", ":fibod:", ":fffibo:"]],
    ["fibo", [":fibo:"]],
    ["дизай", [":fibo:", ":fibod:", ":fffibo:"]],
    ["fibod", [":fibod:"]],
    ["танец", [":fibod:"]],
    ["fffibo", [":fffibo:"]],
    ["ledokol", [":ledokol:", ":lk:"]],
    ["ледокол", [":ledokol:", ":lk:"]],
    ["трактор", [":ledokol:"]],
    ["корабль", [":lk:"]],
    ["атом", [":lk:"]],
    [
        "diablo",
        [
            ":deckard:",
            ":tirael:",
            ":diablo:",
            ":gold:",
            ":moo:",
            ":mana:",
            ":valla:",
        ],
    ],
    [
        "диабло",
        [
            ":deckard:",
            ":tirael:",
            ":diablo:",
            ":gold:",
            ":moo:",
            ":mana:",
            ":valla:",
        ],
    ],
    ["deckard", [":deckard:"]],
    ["декард", [":deckard:"]],
    ["tirael", [":tirael:"]],
    ["тираэль", [":tirael:"]],
    ["gold", [":gold:"]],
    ["голд", [":gold:"]],
    ["золот", [":gold:"]],
    ["богат", [":gold:"]],
    ["moo", [":moo:"]],
    ["коров", [":moo:"]],
    ["mana", [":mana:"]],
    ["мана", [":mana:"]],
    ["valla", [":valla:"]],
]);